###
GET http://localhost:4000/api/employees

###
POST http://localhost:4000/api/employees
content-type: application/json

{
    "name": "Paco7",
    "position": "Master Developer",
    "office": "Sevilla",
    "salary": "154000"
}

###
GET http://localhost:4000/api/employees/65350d337c21715f3cb32a65

###
DELETE  http://localhost:4000/api/employees/653aec88ea6c7ebd58accd31